variables:
  DOCKER_HOST: "unix:///var/run/docker.sock"
  MNEMONIC: $MNEMONIC
  AIRDROP_SCAN_PAGES: $AIRDROP_SCAN_PAGES

stages:
  - prepare
  - patch
  - build
  - test
  - chainspec
  - clean


prepare:
  except:
    - develop
  stage: prepare
  timeout: 60 minutes
  image:
    name: docker/compose
  services:
    - docker:dind
  before_script:
    - mkdir -p target || true
  script:
    - test `docker images|grep polkadot|sed 's/ .*//'` = "polkadot" && echo 'build skipped' || docker-compose -f ./docker-compose-build.yml build polkadot
    - docker build -f ./docker/cicd.Dockerfile -t cicd/$CI_PIPELINE_ID --no-cache .
    - docker run --rm -d --name=cicd-$CI_PIPELINE_ID --entrypoint='/bin/sh' cicd/$CI_PIPELINE_ID -c 'tail -f /dev/null'


patch:
  except:
    - develop
  stage: patch
  timeout: 5 minutes
  image:
    name: docker/compose
  services:
    - docker:dind
  script:
    - docker exec cicd-$CI_PIPELINE_ID nix-shell /shell.nix --run './patches_cmds/subdir_apply_all.sh .'


build:
  except:
    - develop
  stage: build
  timeout: 30 minutes
  image:
    name: docker/compose
  services:
    - docker:dind
  script:
    - docker exec cicd-$CI_PIPELINE_ID nix-shell /shell.nix --run 'cargo build --release --features fast-runtime --features rio-testnet'


test:
  except:
    - develop
  stage: test
  timeout: 30 minutes
  image:
    name: docker/compose
  services:
    - docker:dind
  script:
    - docker exec cicd-$CI_PIPELINE_ID nix-shell /shell.nix --run 'cargo test --release --features fast-runtime --features rio-testnet'


chainspec:
  except:
    - develop
  stage: chainspec
  timeout: 5 minutes
  image:
    name: docker/compose
  services:
    - docker:dind
  before_script:
    - echo "MNEMONIC -> $MNEMONIC"
    - echo "AIRDROP_SCAN_PAGES -> $AIRDROP_SCAN_PAGES"
  script:
    - export AIRDROP_SCAN_PAGES=$AIRDROP_SCAN_PAGES && export MNEMONIC=$MNEMONIC && docker-compose -f ./docker-compose-build.yml build --no-cache --build-arg IMAGE_POLKADOT=cicd/$CI_PIPELINE_ID chainspec

clean:
  except:
    - develop
  stage: clean
  timeout: 5 minutes
  image:
    name: docker/compose
  services:
    - docker:dind
  script:
    - docker container stop cicd-$CI_PIPELINE_ID
    - docker rmi --force cicd/$CI_PIPELINE_ID
#    - docker rm cicd-$CI_PIPELINE_ID

