version: '3.7'

services:

  polkadot:
    image: polkadot
    build:
      context: .
      dockerfile: ./docker/polkadot.Dockerfile
      args:
        NIX_VERSION: 2.3.12
        NIX_TAG: d9bb3b85b846eb0b6c5204e0d76639dff72c7871fb68f5d4edcfbb727f8a5653

  chainspec:
    image: chainspec
    depends_on:
      - polkadot
    build:
      context: .
      dockerfile: ./docker/chainspec.Dockerfile
      args:
        MNEMONIC: ${MNEMONIC}
        AIRDROP_SCAN_PAGES: ${AIRDROP_SCAN_PAGES:-700}
        IMAGE_POLKADOT: polkadot
        RELAY_FILE_FROM: /rio/chainspec/polkadot-plain.json
        RELAY_FILE_TO: /rio/chainspec/polkadot-custom.json
        RELAY_RAW: /rio/chainspec/polkadot-raw.json
        PARA_FILE_FROM: /rio/chainspec/parachain-plain.json
        PARA_FILE_TO: /rio/chainspec/parachain-custom.json
        PARA_RAW: /rio/chainspec/parachain-raw.json
        PARA_WASM: /rio/chainspec/para-2000-wasm
        PARA_GENESIS: /rio/chainspec/para-2000-genesis
    entrypoint: /rio/src/docker/scripts/build_chainspec.sh
    volumes:
      - .chainspec:/rio/chainspec
      - .keys:/rio/keys
      - ./docker:/rio/src/docker
    environment:
      MNEMONIC: ${MNEMONIC}
      AIRDROP_SCAN_PAGES: ${AIRDROP_SCAN_PAGES:-10}
      RELAY_FILE_FROM: /rio/chainspec/polkadot-plain.json
      RELAY_FILE_TO: /rio/chainspec/polkadot-custom.json
      RELAY_RAW: /rio/chainspec/polkadot-raw.json
      PARA_FILE_FROM: /rio/chainspec/parachain-plain.json
      PARA_FILE_TO: /rio/chainspec/parachain-custom.json
      PARA_RAW: /rio/chainspec/parachain-raw.json
      PARA_WASM: /rio/chainspec/para-2000-wasm
      PARA_GENESIS: /rio/chainspec/para-2000-genesis

  runner:
    image: runner
    depends_on:
      - chainspec
    build:
      context: .
      dockerfile: ./docker/runner.Dockerfile
      args:
        #IMAGE_CHAINSPEC: chainspec
        #IMAGE_POLKADOT: polkadot
        NIX_LIB: /nix/store/z56jcx3j1gfyk4sv7g8iaan0ssbdkhz1-glibc-2.33-56
