version: '3.7'

x-relay-node: &relay-node
  image: runner
  working_dir: /rio/src
  entrypoint: /rio/start_relay.sh
  networks:
    - polkadot-local
  volumes:
    #- .chainspec:/rio/chainspec
    #- .keys:/rio/keys
    - ./docker/scripts/start_collator_local.sh:/rio/start_collator.sh
    - ./docker/scripts/start_relay_local.sh:/rio/start_relay.sh

x-collator: &collator
  <<: *relay-node
  entrypoint: /rio/start_collator.sh

services:

  relay-node-01:
    <<: *relay-node
    # to attach and debug
    #entrypoint: tail -f /dev/null
    ports:
      - "443:9944"
      - "41001:9944"
      - "42001:9433"
    environment:
      ACCOUNT: 1
      WS_PORT: 9944
      RPC_PORT: 9933
      BASE_PATH: /rio/keys/relay-01
      RELAY_RAW: /rio/chainspec/polkadot-raw.json

  relay-node-02:
    <<: *relay-node
    ports:
      - "41002:9944"
      - "42002:9433"
    environment:
      WS_PORT: 9944
      RPC_PORT: 9933
      ACCOUNT: 2
      BASE_PATH: /rio/keys/relay-02
      RELAY_RAW: /rio/chainspec/polkadot-raw.json

  relay-node-03:
    <<: *relay-node
    ports:
      - "41003:9944"
      - "42003:9433"
    environment:
      WS_PORT: 9944
      RPC_PORT: 9933
      ACCOUNT: 3
      RELAY_RAW: /rio/chainspec/polkadot-raw.json

  relay-node-04:
    <<: *relay-node
    ports:
      - "41004:9944"
      - "42004:9433"
    environment:
      WS_PORT: 9944
      RPC_PORT: 9933
      ACCOUNT: 4
      RELAY_RAW: /rio/chainspec/polkadot-raw.json

  relay-node-05:
    <<: *relay-node
    ports:
      - "41005:9944"
      - "42005:9433"
    environment:
      WS_PORT: 9944
      RPC_PORT: 9933
      ACCOUNT: 5
      RELAY_RAW: /rio/chainspec/polkadot-raw.json

  relay-node-06:
    <<: *relay-node
    ports:
      - "41006:9944"
      - "42006:9433"
    environment:
      WS_PORT: 9944
      RPC_PORT: 9933
      ACCOUNT: 6
      RELAY_RAW: /rio/chainspec/polkadot-raw.json

  collator-node-01:
    <<: *collator
    ports:
      - "43001:9944"
      - "44001:9433"
    environment:
      WS_PORT: 9944
      RPC_PORT: 9933
      ACCOUNT: 1
      RELAY_RAW: /rio/chainspec/polkadot-raw.json
      PARA_RAW: /rio/chainspec/parachain-raw.json

  collator-node-02:
    <<: *collator
    ports:
      - "43002:9944"
      - "44002:9433"
    environment:
      WS_PORT: 9944
      RPC_PORT: 9933
      ACCOUNT: 2
      RELAY_RAW: /rio/chainspec/polkadot-raw.json
      PARA_RAW: /rio/chainspec/parachain-raw.json

  collator-node-03:
    <<: *collator
    ports:
      - "43003:9944"
      - "44003:9433"
    environment:
      WS_PORT: 9944
      RPC_PORT: 9933
      ACCOUNT: 3
      RELAY_RAW: /rio/chainspec/polkadot-raw.json
      PARA_RAW: /rio/chainspec/parachain-raw.json

networks:
  polkadot-local:
