version: '3.7'

services:

#  prometeus:
#    image: prom/prometheus

#  grafana:
#    image: grafana/grafana-oss

  build-chainspec:
    image: polkadot
    working_dir: /tmp/riochain/target/release/
    #entrypoint: tail -f /dev/null
    entrypoint: /tmp/entrypoint.sh
    volumes:
            #- /tmp/debug:/debug
      - tmp:/tmp
      - ./docker1/scripts/build_chainspec.sh:/tmp/entrypoint.sh
      - ./docker1:/tmp/docker1
    environment:
      FILE_ACCOUNTS: /tmp/accounts.json
      MNEMONIC: 'chronic scene situate genuine advice gospel lady obvious blood palace economy marble'

#  tmp:
#    depends_on:
#      build-chainspec:
#        condition: service_completed_successfully
#    image: polkadot
#    working_dir: /tmp/polkadot/target/release/
#    entrypoint: tail -f /dev/null
#    networks:
#      - polkadot-local
#    volumes:
#      - tmp:/tmp
#      - ./docker1/scripts/start_polkadot.sh:/tmp/entrypoint.sh
#      - ./docker1/.chainspec:/tmp/chainspec
#      - ./docker1:/docker

  relay-node-01:
    image: polkadot
    working_dir: /tmp/riochain/target/release/
    #entrypoint: tail -f /dev/null
    entrypoint: /tmp/entrypoint.sh
    networks:
      - polkadot-local
    volumes:
      # - /tmp/debug2:/debug
      - tmp:/tmp
      - ./docker1/scripts/start_polkadot.sh:/tmp/entrypoint.sh
      - ./docker1:/tmp/docker1
    ports:
      - "41001:9944"
      - "42001:9615"
    environment:
      ACCOUNT: 1
      NODE_KEY: '0400000000000000000000000000000000000000000000000000000000000001'
      CHAINSPEC_RAW: /tmp/docker1/.chainspec/polkadot-custom-2-raw.json
      #CHAINSPEC_RAW: /tmp/docker1/.chainspec/rococo-custom-2-raw.json
      BASE_PATH: /tmp/node-01

  relay-node-02:
    image: polkadot
    working_dir: /tmp/riochain/target/release/
    entrypoint: /tmp/entrypoint.sh
    networks:
      - polkadot-local
    volumes:
      - tmp:/tmp
      - ./docker1/scripts/start_polkadot.sh:/tmp/entrypoint.sh
      - ./docker1:/tmp/docker1
    ports:
      - "41002:9944"
      - "42002:9615"
    environment:
      ACCOUNT: 2
      NODE_KEY: '0400000000000000000000000000000000000000000000000000000000000002'
      CHAINSPEC_RAW: /tmp/docker1/.chainspec/polkadot-custom-2-raw.json
      #CHAINSPEC_RAW: /tmp/docker1/.chainspec/rococo-custom-2-raw.json
      BASE_PATH: /tmp/node-02

  relay-node-03:
    image: polkadot
    working_dir: /tmp/riochain/target/release/
    entrypoint: /tmp/entrypoint.sh
    networks:
      - polkadot-local
    volumes:
      - tmp:/tmp
      - ./docker1/scripts/start_polkadot.sh:/tmp/entrypoint.sh
      - ./docker1:/tmp/docker1
    ports:
      - "41003:9944"
      - "42003:9615"
    environment:
      ACCOUNT: 3
      NODE_KEY: '0400000000000000000000000000000000000000000000000000000000000003'
      CHAINSPEC_RAW: /tmp/docker1/.chainspec/polkadot-custom-2-raw.json
      #CHAINSPEC_RAW: /tmp/docker1/.chainspec/rococo-custom-2-raw.json
      BASE_PATH: /tmp/node-03

  relay-node-04:
    image: polkadot
    working_dir: /tmp/riochain/target/release/
    entrypoint: /tmp/entrypoint.sh
    networks:
      - polkadot-local
    volumes:
      - tmp:/tmp
      - ./docker1/scripts/start_polkadot.sh:/tmp/entrypoint.sh
      - ./docker1:/tmp/docker1
    ports:
      - "41004:9944"
      - "42004:9615"
    environment:
      ACCOUNT: 4
      NODE_KEY: '0400000000000000000000000000000000000000000000000000000000000004'
      CHAINSPEC_RAW: /tmp/docker1/.chainspec/polkadot-custom-2-raw.json
      #CHAINSPEC_RAW: /tmp/docker1/.chainspec/rococo-custom-2-raw.json
      BASE_PATH: /tmp/node-04

  relay-node-05:
    image: polkadot
    working_dir: /tmp/riochain/target/release/
    entrypoint: /tmp/entrypoint.sh
    networks:
      - polkadot-local
    volumes:
      - tmp:/tmp
      - ./docker1/scripts/start_polkadot.sh:/tmp/entrypoint.sh
      - ./docker1:/tmp/docker1
    ports:
      - "41005:9944"
      - "42005:9615"
    environment:
      ACCOUNT: 5
      NODE_KEY: '0400000000000000000000000000000000000000000000000000000000000005'
      CHAINSPEC_RAW: /tmp/docker1/.chainspec/polkadot-custom-2-raw.json
      BASE_PATH: /tmp/node-05

  relay-node-06:
    image: polkadot
    working_dir: /tmp/riochain/target/release/
    entrypoint: /tmp/entrypoint.sh
    networks:
      - polkadot-local
    volumes:
      - tmp:/tmp
      - ./docker1/scripts/start_polkadot.sh:/tmp/entrypoint.sh
      - ./docker1:/tmp/docker1
    ports:
      - "41006:9944"
      - "42006:9615"
    environment:
      ACCOUNT: 6
      NODE_KEY: '0400000000000000000000000000000000000000000000000000000000000006'
      CHAINSPEC_RAW: /tmp/docker1/.chainspec/polkadot-custom-2-raw.json
      BASE_PATH: /tmp/node-06

  collator-node-01:
    image: polkadot
    working_dir: /tmp/riochain/target/release/
    entrypoint: /tmp/entrypoint.sh
    networks:
      - polkadot-local
    volumes:
      - tmp:/tmp
      - ./docker1/scripts/start_collator.sh:/tmp/entrypoint.sh
      - ./docker1:/tmp/docker1
    ports:
      - "43001:9944"
      - "44001:9615"
    environment:
      ACCOUNT: 7
      NODE_KEY: '0500000000000000000000000000000000000000000000000000000000000001'
      CHAINSPEC_RAW: /tmp/docker1/.chainspec/polkadot-custom-2-raw.json
      PARA_CHAINSPEC_RAW: /tmp/docker1/.chainspec/parachain-rio-custom-raw.json
      BASE_PATH: /tmp/node-07

  collator-node-02:
    image: polkadot
    working_dir: /tmp/riochain/target/release/
    entrypoint: /tmp/entrypoint.sh
    networks:
      - polkadot-local
    volumes:
      - tmp:/tmp
      - ./docker1/scripts/start_collator.sh:/tmp/entrypoint.sh
      - ./docker1:/tmp/docker1
    ports:
      - "43002:9944"
      - "44002:9615"
    environment:
      ACCOUNT: 8
      NODE_KEY: '0500000000000000000000000000000000000000000000000000000000000002'
      CHAINSPEC_RAW: /tmp/docker1/.chainspec/polkadot-custom-2-raw.json
      PARA_CHAINSPEC_RAW: /tmp/docker1/.chainspec/parachain-rio-custom-raw.json
      BASE_PATH: /tmp/node-08

  collator-node-03:
    image: polkadot
    working_dir: /tmp/riochain/target/release/
    entrypoint: /tmp/entrypoint.sh
    networks:
      - polkadot-local
    volumes:
      - tmp:/tmp
      - ./docker1/scripts/start_collator.sh:/tmp/entrypoint.sh
      - ./docker1:/tmp/docker1
    ports:
      - "43003:9944"
      - "44003:9615"
    environment:
      ACCOUNT: 9
      NODE_KEY: '0500000000000000000000000000000000000000000000000000000000000003'
      CHAINSPEC_RAW: /tmp/docker1/.chainspec/polkadot-custom-2-raw.json
      PARA_CHAINSPEC_RAW: /tmp/docker1/.chainspec/parachain-rio-custom-raw.json
      BASE_PATH: /tmp/node-09

networks:
  polkadot-local:

volumes:
  tmp:
