#!/bin/sh
ln -sf ../../submodules/aframe/precompiles/assets-erc20/ERC20.sol precompiles/assets-erc20/ERC20.sol
ln -sf ../../submodules/aframe/precompiles/utils/macro precompiles/utils/macro
ln -sf ../../submodules/aframe/precompiles/utils/src precompiles/utils/src
ln -sf ../../submodules/polkadot/node/client/src node/relaychain-rio-client/src
ln -sf ../../submodules/polkadot/cli/build.rs node/relaychain-rio-cli/build.rs
ln -sf ../../../submodules/polkadot/cli/src/lib.rs node/relaychain-rio-cli/src/lib.rs
ln -sf ../../../submodules/polkadot/cli/src/error.rs node/relaychain-rio-cli/src/error.rs
ln -sf ../../../submodules/polkadot/cli/src/host_perf_check.rs node/relaychain-rio-cli/src/host_perf_check.rs
ln -sf ../../../submodules/polkadot/cli/src/cli.rs node/relaychain-rio-cli/src/cli.rs
ln -sf ../../../submodules/polkadot/node/service/src/relay_chain_selection.rs node/relaychain-rio-service/src/relay_chain_selection.rs
ln -sf ../../../submodules/polkadot/node/service/src/parachains_db node/relaychain-rio-service/src/parachains_db
ln -sf ../../../submodules/polkadot/node/service/src/lib.rs node/relaychain-rio-service/src/lib.rs
ln -sf ../../../submodules/polkadot/node/service/src/overseer.rs node/relaychain-rio-service/src/overseer.rs
ln -sf ../../../submodules/polkadot/node/service/src/grandpa_support.rs node/relaychain-rio-service/src/grandpa_support.rs
ln -sf ../../../submodules/polkadot/src/main.rs node/relaychain-rio/src/main.rs
ln -sf ../../../../submodules/substrate/frame/transaction-payment/rpc/src/lib.rs pallets/transaction-payment/rpc/src/lib.rs
ln -sf ../../../../../submodules/substrate/frame/transaction-payment/rpc/runtime-api/src/lib.rs pallets/transaction-payment/rpc/runtime-api/src/lib.rs
ln -sf ../../../submodules/substrate/frame/transaction-payment/src/payment.rs pallets/transaction-payment/src/payment.rs
ln -sf ../../../submodules/substrate/frame/transaction-payment/src/lib.rs pallets/transaction-payment/src/lib.rs
ln -sf ../../../submodules/substrate/frame/transaction-payment/src/types.rs pallets/transaction-payment/src/types.rs
ln -sf ../../submodules/polkadot/runtime/common/slot_range_helper runtime/common-rio/slot_range_helper
ln -sf ../../submodules/polkadot/runtime/common/src runtime/common-rio/src
ln -sf ../../../../submodules/polkadot/runtime/polkadot/constants/src/weights runtime/relaychain-rio/constants/src/weights
ln -sf ../../submodules/polkadot/runtime/polkadot/build.rs runtime/relaychain-rio/build.rs
ln -sf ../../../submodules/polkadot/runtime/polkadot/src/bag_thresholds.rs runtime/relaychain-rio/src/bag_thresholds.rs
ln -sf ../../../submodules/polkadot/runtime/polkadot/src/weights runtime/relaychain-rio/src/weights
