AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "rio-node"
      ImageScanningConfiguration:
        ScanOnPush: "true" # security check
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          -
            Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                #- arn:aws:iam::<prod_prj_id>:root
                - arn:aws:iam::061416964074:root
            Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:BatchGetImage
              - ecr:CompleteLayerUpload
              - ecr:GetDownloadUrlForLayer
              - ecr:InitiateLayerUpload
              - ecr:PutImage
              - ecr:UploadLayerPart
      Tags:
        - Key: Name
          Value: rio-node-ecr
        - Key: ENVIRONMENT
          Value: non-prd
